import argparse
from pathlib import Path

import numpy as np

from src.wsi.reader import WSIReader
from src.wsi.tiler import WSITiler
from src.wsi.tissue import make_tissue_mask


def main():
    parser = argparse.ArgumentParser(
        description="Run the WSI pipeline on a normal image via OpenSlide ImageSlide."
    )
    parser.add_argument(
        "image",
        type=str,
        help="PNG/JPG demo image generated by make_demo_slide.py",
    )
    parser.add_argument(
        "--tile-size",
        type=int,
        default=256,
    )
    parser.add_argument(
        "--max-tiles",
        type=int,
        default=10,
    )
    args = parser.parse_args()

    image_path = Path(args.image)

    if not image_path.exists():
        raise FileNotFoundError(f"Demo image not found: {image_path}")

    # This demonstrates the same reader/tiler logic on a normal image.
    # OpenSlide's ImageSlide wrapper exposes an OpenSlide-compatible API.
    import openslide

    slide = openslide.ImageSlide(str(image_path))

    class ImageSlideReader:
        def __init__(self, image, path):
            self.slide = image
            self.path = path

        def __enter__(self):
            return self

        def __exit__(self, exc_type, exc_val, exc_tb):
            self.close()

        def close(self):
            self.slide.close()

        @property
        def dimensions(self):
            return self.slide.dimensions

        def thumbnail(self, max_width=2048, max_height=2048):
            return self.slide.get_thumbnail(
                (max_width, max_height)
            ).convert("RGB")

        def read_region_array(self, x, y, level, width, height):
            return np.asarray(
                self.slide.read_region(
                    (int(x), int(y)),
                    int(level),
                    (int(width), int(height)),
                ).convert("RGB")
            )

    with ImageSlideReader(slide, image_path) as reader:
        thumbnail = reader.thumbnail()
        mask = make_tissue_mask(thumbnail)

        tiler = WSITiler(
            reader=reader,
            tissue_mask=mask,
            tile_size=args.tile_size,
            min_tissue_fraction=0.25,
        )

        tiles = tiler.collect(max_tiles=args.max_tiles)

        print(f"Image dimensions : {reader.dimensions}")
        print(f"Thumbnail shape  : {thumbnail.size}")
        print(f"Tissue fraction  : {mask.mean():.3f}")
        print(f"Selected tiles   : {len(tiles)}")

        if tiles:
            patch = tiler.read_tile(tiles[0])
            print(f"First patch shape: {patch.shape}")

    print("\nWSI pipeline dry run PASSED.")


if __name__ == "__main__":
    main()
